### ISSUE TITLE
.ini file recognised as Mpeg1AudioLayer1 in Windows

### ISSUE THREAD

**Issue by Siirko** [mmalecot/file-format#36]
Hello !

It seems that when trying to find the type of a .ini file in Windows, it detects as a MpegAudioLayer1
![image](https://github.com/mmalecot/file-format/assets/77932724/decec7b3-e026-47ae-896f-c948ee6b56b0)

It is kinda problematic when you want to filter out audio file ... 

I'm kinda sure that error doesn't come from [my code ](https://github.com/Siirko/symfoniya/blob/da17f09a55c1c3cdd80b907b05436ba9e64ac18a/src-tauri/src/music/audio.rs#L240), current fix is to skip .ini files

**Comment by mmalecot** [comment]
Hello,

Thank you for your message.

You're right, and I've already seen this problem. I'll see if I can find a solution, and I'll keep you posted.

**Comment by mmalecot** [comment]
The problem is that one of the signatures of the MP1 format is also the UTF-16LE BOM. Windows often encodes its text files using this encoding, which includes the famous desktop.ini files.

So in reality, any text file encoded in UTF-16LE is currently considered to be an MP1 with `file-format`.

The only solution I've found is to exclude this signature of the MP1 format. `libmagic` doesn't this format, but rather than no longer manage it, I'd rather just ignore this signature, which is likely to cause problems far too often.

I'm going to make a `file-format` patch to fix this, so you'll need to update the version of the dependency in your `Cargo.toml`. 

You might also want to enable some of the reader features of the crate (see on docs.rs) as there are some audio file formats that are only detected with these features (e.g. WMA, MKA and RA).

It will certainly be version 0.20.1.

**Comment by mmalecot** [comment]
Done on the `dev` branch, it will be available with version 0.21.

**Comment by mmalecot** [comment]
Version 0.21.0 has been published, including this patch (drop of the MP1 format support).
You can update your Cargo.toml.
