### ISSUE TITLE
How are some files categorized

### ISSUE THREAD

**Issue by 448-OG** [mmalecot/file-format#37]
How are some files categorized using the `.kind()` method?

For example https://github.com/jvns/dnspeep/releases/download/v0.1.3/dnspeep-linux.tar.gz is categorized as an application even though it is packaged as a compressed file. The compressed file contains a binary so does that mean it reads the file and instead of showing that the file kind is compressed instead it detects the binary inside the compressed file and returns the `Kind` as `Kind::Application`  but I would expect it to return `Kind::Compression` so that if I want to search all compressed files I would just match on `Kind::Compression`?

Similary, a simple Txt file containing the words `Foo Bar` is read as an `Kind::Application` with media type `application/octet-stream` ?

PDF files are classified  as Kind::Application , wouldnt they be classified as Kind::Document ?

My question, is this how the library works or is it a bug

**Comment by 448-OG** [comment]
For text files I have solved that by activating features "accuracy-txt".

**Comment by mmalecot** [comment]
Each file format has its own kind, which can be accessed from the crate documentation at `docs.rs`.

This may vary between `file-format` versions, as some formats are categorised rather than staying with the generic `Kind::Application` type, which groups together all non-categorised formats (because they are sometimes specific to an application).

With the latest `file-format` version, currently `0.20`, your .gz file will be categorised as `Kind::Compression`, a PDF file will be categorised as `Kind::Document,` and a text file as `Kind::Text`.

I think you're using an old version of the crate, as the accuracy features no longer exist.

**Comment by 448-OG** [comment]
Thanks. My Cargo.lock file was using an older format. I have updated and everything seem to work properly. Your library is a awesome when categorizing files :)
