### ISSUE TITLE
Add support for APPX Bundles

### ISSUE THREAD

**Issue by russellbanks** [mmalecot/file-format#43]
`.msixbundle` and `.appxbundle` are bundles of MSIXs or APPXs respectively.

These can be detected in a similar way to APPXs. Instead of an `AppxManifest.xml` at the root of the archive, the bundles have an `AppxBundleManifest.xml` under the `AppxMetadata` folder.

**Comment by mmalecot** [comment]
Thanks for this issue!

I'll look into this for the next version of `file-format`. 

On the other hand, it seems a bit complicated to differentiate MSIX files from APPX files (and therefore MSIX Bundle files from APPX Bundle files) because MSIX is just the more modern version of APPX.

I think that initially I can manage the APPX Bundle format: we'll see later if it's possible and necessary to add MSIX and MSIX Bundle.

**Comment by russellbanks** [comment]
I use the words APPX and MSIX interchangeably as they're fundamentally the same and identified the same. This issue is specifically for their bundle equivalents.

**Comment by mmalecot** [comment]
Thank you for your time!
I'll look into it.

**Comment by mmalecot** [comment]
Done on `dev` branch.
