### ISSUE TITLE
Add info to readme with comparison with infer

### ISSUE THREAD

**Issue by qarmin** [mmalecot/file-format#62]

**Comment by mmalecot** [comment]
I don't like to compare my projects with those of others, because I wouldn't be objective, so I let the community do it if it's necessary.

The only thing I can say is that `file-format` detects many more file formats than `infer` but not only serves as a detection tool but also provides a lot of information about file formats such as their kind, name, extension and so on. On the other hand, `infer` mights be lighter and faster if you need to detect classic file formats.
